# Introduction to QuTip for Quantum Problems
From QuTiP's documentation:   
> QuTiP is a python package for calculations and numerical simulations of quantum systems.   
> It includes facilities for representing and doing calculations with quantum objects such state vectors (wavefunctions), as bras/kets/density matrices, quantum operators of single and composite systems, and superoperators (useful for defining master equations).   
> It also includes solvers for a time-evolution of quantum systems, according to: Schrodinger equation, von Neuman equation, master equations, Floquet formalism, Monte-Carlo quantum trajectors, experimental implementations of the stochastic Schrodinger/master equations.
   
This notebook follows along as I read through the paper [*Undergraduate Quantum Mechanics: a Numerical Approach using QuTiP*.](Undergraduate_Quantum_Mechanics_a_Numerical_Approach.pdf)

## A Quick (and incomplete) Intro to QuTiP
Python is an *object-oriented* language: an *object* is more-or-less self-contained and has both attributes and methods (functions). You can think of an object as a physical system. This system can act and be acted upon.
### Qobj()
The object at the core of our `QuTiP` experiments is the `Qobj`. A `Qobj` is a matrix or a vector, and contains attributes that describe the object, like its dimensions and whether it is a bra or a ket state. We will demonstrate the concept of a Qobj, but first let's import the Python packages we will need inorder to work with QuTip:

In [1]:
# First import qutip:
from qutip import * # the asterisk is a wildcard, basically meaning 'all'
# Now import numpy, which contains useful math functionality and matrix/array implementation that is FAST and 
# EFFICIENT because it's actually based in C
import numpy as np
from numpy import sqrt, pi, array, sin, cos, arange
# Finally, import matplotlib, which allows us to plot things using syntax familiar to MATLAB users.
import matplotlib.pyplot as plt

Now that we have our necessary dependencies, let's create some quantum objects. Start with a blank object:

In [2]:
q1 = Qobj()
print(q1)

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.]]


We can see that `q1` is a 1x1 bra object with a single zero entry. Now let's try specifying some data when we create `q1`:

In [3]:
q1 = Qobj([[1],[2],[3],[4],[5]])
print(q1)

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]


We can see that `q1` is a ket vector with $$ \langle q_1 \vert = \begin{pmatrix}1&2&3&4&5\end{pmatrix}.$$
What if we input a column vector instead of a row vector when constructing `q1`?

In [4]:
q1 = Qobj(np.array([[1,2,3,4,5]]))
print(q1)

Quantum object: dims = [[1], [5]], shape = (1, 5), type = bra
Qobj data =
[[1. 2. 3. 4. 5.]]


We can see that `q1` is a bra object with $$ \vert q_1 \rangle = \begin{pmatrix}1\\2\\3\\4\\5\end{pmatrix}. $$
Let's try inputting a 2x2 matrix into `Qobj()`:

In [5]:
q1 = Qobj(np.array([[1,0],[0,-1]]))
print(q1)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]


Here we can see that a quantum object created with the input $$ \begin{pmatrix} 1 & 0 \\ 0 & -1\end{pmatrix} $$ is a hermitian operator. Notice that if we multiply this input matrix by $ \frac{\hbar}{2} $, we get the hermitian operator for the spin operator along the z-axis.
### basis()
QuTip contains tools to construct objects that are frequently used, one of which is `basis()`, a function to create basis vectors for a Hilbert space. This function is used as `basis(N,m)`, where `N` is the number of levels in the space and `m` is the excited level of the basis vector (all other levels are 0). Let's examine this:

In [6]:
print(basis(2,1))

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]


As you can see, for $ N=2, m=1 $ , the basis vector is $ \begin{pmatrix} 0\\1 \end{pmatrix}. $

## Photon Polarization States